# Generated by Django 4.1.4 on 2022-12-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_localization', models.IntegerField()),
                ('y_localization', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
